name    'justinstoller/rubyinstaller'
version '0.0.1'
source 'git://github.com/justinstoller/puppet-rubyinstaller.git'
author 'justinstoller'
license 'Apache License, Version 2.0'
summary 'Install versions of Ruby on Windows'
description 'Install the latest versions Ruby 1.8 and 1.9 on Windows systems using the RubyInstaller (rubyinstaller.org)'
project_page 'https://github.com/justinstoller/puppet-rubyinstaller'
